/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void generate_interrupt()
{
	uint32_t *pSTIR = (uint32_t *)0xE000EF00;
	uint32_t *pISER0 = (uint32_t *)0xE000E100;

	//ENABLE IRQ3 INTERRUPT//
	*pISER0 |= (1<<3);

	//GENERATE AN INTERRUPT FROM SW FOR IRQ3
	*pSTIR = (3 & 0x1FF);

}
void change_to_unp()
{

}
int main(void)
{
	printf("in thread mode: before interrupt\n");
	generate_interrupt();
	printf("in thread mode: after interrupt\n");
    /* Loop forever */
	for(;;);
}
