/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#define ADDRESS
#define ALIAS_BASE
#define BITBAND_BASE

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint8_t *ptr = (uint8_t *)ADDRESS;
	*ptr = 0xff;
	*ptr &= ~(1<<7);

	uint8_t *alias = (uint8_t *)(ALIAS_BASE+(32*(ADDRESS-BITBAND_BASE))+7*4);
    /* Loop forever */
	for(;;);
}
